repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0 # Use the ref you want to point at
  hooks:
    - id: end-of-file-fixer
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    args: [--config=pyproject.toml]
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--sp=pyproject.toml]
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
- repo: https://github.com/asottile/pyupgrade
  rev: v3.11.1
  hooks:
    - id: pyupgrade
      args: [--py310-plus]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.36.0
  hooks:
  - id: markdownlint
